// Generated by Framer (07ac007)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    forwardLoader,
    getFonts,
    getFontsFromSharedStyle,
    getPropertyControls,
    RichText,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/j13RV7ugRmCQlHOvDOmQ/crE6qHGq5HB9tW6wFOVx/J3hYbVXRC.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/QKddRqMA0XheLEoIV1I1/49XIpOocKU2woMFrBrqC/Kf8J2YAVU.js";
import ContentColorPattern from "https://framerusercontent.com/modules/vrWYTMOn0ZABNBfFZyG7/Nf1ETuSU3sVkVV6eaOc9/LUbgkKF68.js";
const ContentColorPatternFonts = getFonts(ContentColorPattern);
const ContentColorPatternControls = getPropertyControls(ContentColorPattern);
const cycleOrder = ["a_i3Ojz3q", "oIasTG3xn"];
const serializationHash = "framer-OEX4H";
const variantClassNames = {
    a_i3Ojz3q: "framer-v-n3c2vp",
    oIasTG3xn: "framer-v-17pzkuy"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const iYSCSMicO = undefined;
const QtQXVcL4H = undefined;
const ScBCWp05W = undefined;
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const matchVariant = (...args) => {
    for (const arg of args) {
        if (arg && typeof arg === "string") return arg;
    }
    return undefined;
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    Desktop: "a_i3Ojz3q",
    Mobile: "oIasTG3xn"
};
const Variants = motion.create(React.Fragment);
const humanReadableEnumMap = {
    "Blue ": "Kpz8UOaS9",
    "Green ": "VoxYlBpoN",
    "Purple ": "VhAdZ2ojK",
    Orange: "OHtDswQo5",
    Yellow: "EpmFPoKL_"
};
const getProps = ({
    colorVersion,
    height,
    id,
    text,
    title,
    width,
    ...props
}) => {
    return { ...props,
        iYSCSMicO: humanReadableEnumMap[colorVersion] ? ? colorVersion ? ? props.iYSCSMicO ? ? "VhAdZ2ojK",
        QtQXVcL4H: title ? ? props.QtQXVcL4H ? ? "Adaptive Intelligence",
        ScBCWp05W: text ? ? props.ScBCWp05W ? ? "Prospect learns how you work and adapts in real time. No retraining, no friction—just a system that evolves with your pace and priorities.",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "a_i3Ojz3q"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        iYSCSMicO,
        QtQXVcL4H,
        ScBCWp05W,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "a_i3Ojz3q",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-n3c2vp", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "a_i3Ojz3q",
                    ref: refBinding,
                    style: {
                        backdropFilter: "blur(14px)",
                        backgroundColor: "var(--token-0f516fd4-65c7-4b64-880e-09084b80b9c7, rgb(255, 255, 255))",
                        borderBottomLeftRadius: 12,
                        borderBottomRightRadius: 12,
                        borderTopLeftRadius: 12,
                        borderTopRightRadius: 12,
                        boxShadow: "0px 4px 18px 0px rgba(0, 0, 0, 0.12)",
                        WebkitBackdropFilter: "blur(14px)",
                        ...style
                    },
                    ...addPropertyOverrides({
                        oIasTG3xn: {
                            "data-framer-name": "Mobile"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-123scdn",
                        "data-framer-name": "Wrap",
                        layoutDependency: layoutDependency,
                        layoutId: "Wnv9aA5wX",
                        children: /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-117x4k4",
                            "data-framer-name": "Image",
                            layoutDependency: layoutDependency,
                            layoutId: "OWpAiOid8",
                            children: /*#__PURE__*/ _jsx(motion.div, {
                                className: "framer-egtimb",
                                "data-framer-name": "Content / Color Pattern",
                                layoutDependency: layoutDependency,
                                layoutId: "nKNynIeyk",
                                children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 80,
                                    width: componentViewport ? .width || "100vw",
                                    y: (componentViewport ? .y || 0) + 0 + 0 + 0 + 0 + 0 + 0,
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1aiviiv-container",
                                        layoutDependency: layoutDependency,
                                        layoutId: "qMa6_Do5K-container",
                                        nodeId: "qMa6_Do5K",
                                        rendersWithMotion: true,
                                        scopeId: "zQZfnmNZX",
                                        children: /*#__PURE__*/ _jsx(ContentColorPattern, {
                                            height: "100%",
                                            id: "qMa6_Do5K",
                                            layoutId: "qMa6_Do5K",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            variant: matchVariant(iYSCSMicO),
                                            width: "100%"
                                        })
                                    })
                                })
                            })
                        })
                    }), /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-vb59dg",
                        "data-framer-name": "Card Content",
                        layoutDependency: layoutDependency,
                        layoutId: "Ri02nI85B",
                        children: [ /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h5, {
                                    className: "framer-styles-preset-13ijui5",
                                    "data-styles-preset": "J3hYbVXRC",
                                    dir: "auto",
                                    children: "Adaptive Intelligence"
                                })
                            }),
                            className: "framer-mw4re9",
                            "data-framer-name": "Title",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "YJuG067Ts",
                            style: {
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: QtQXVcL4H,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-axbvaz",
                                    "data-styles-preset": "Kf8J2YAVU",
                                    dir: "auto",
                                    children: "Prospect learns how you work and adapts in real time. No retraining, no friction—just a system that evolves with your pace and priorities."
                                })
                            }),
                            className: "framer-19ebhd6",
                            "data-framer-name": "Text",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "oB9Qty4Fc",
                            style: {
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: ScBCWp05W,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })]
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-OEX4H.framer-1bfv5no, .framer-OEX4H .framer-1bfv5no { display: block; }", ".framer-OEX4H.framer-n3c2vp { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: 400px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 296px; will-change: var(--framer-will-change-override, transform); }", ".framer-OEX4H .framer-123scdn { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }", ".framer-OEX4H .framer-117x4k4 { flex: none; gap: 0px; height: 64px; overflow: hidden; position: relative; width: 100%; }", ".framer-OEX4H .framer-egtimb { flex: none; height: 100%; left: 0px; position: absolute; top: 0px; width: 100%; }", ".framer-OEX4H .framer-1aiviiv-container { flex: none; height: 80px; left: 0px; position: absolute; top: 0px; width: 100%; }", ".framer-OEX4H .framer-vb59dg { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: 1px; justify-content: flex-start; overflow: visible; padding: 0px 24px 24px 24px; position: relative; width: 100%; }", ".framer-OEX4H .framer-mw4re9, .framer-OEX4H .framer-19ebhd6 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }", ".framer-OEX4H.framer-v-17pzkuy.framer-n3c2vp { height: min-content; }", ".framer-OEX4H.framer-v-17pzkuy .framer-vb59dg { flex: none; height: min-content; }", ...sharedStyle.css, ...sharedStyle1.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 400
 * @framerIntrinsicWidth 296
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"oIasTG3xn":{"layout":["fixed","auto"]}}}
 * @framerVariables {"iYSCSMicO":"colorVersion","QtQXVcL4H":"title","ScBCWp05W":"text"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerzQZfnmNZX = withCSS(Component, css, "framer-OEX4H");
export default FramerzQZfnmNZX;
FramerzQZfnmNZX.displayName = "Feature Card";
FramerzQZfnmNZX.defaultProps = {
    height: 400,
    width: 296
};
addPropertyControls(FramerzQZfnmNZX, {
    variant: {
        options: ["a_i3Ojz3q", "oIasTG3xn"],
        optionTitles: ["Desktop", "Mobile"],
        title: "Variant",
        type: ControlType.Enum
    },
    iYSCSMicO: ContentColorPatternControls ? .["variant"] && { ...ContentColorPatternControls["variant"],
        defaultValue: "VhAdZ2ojK",
        description: undefined,
        hidden: undefined,
        title: "Color Version"
    },
    oniYSCSMicOChange: {
        changes: "iYSCSMicO",
        type: ControlType.ChangeHandler
    },
    QtQXVcL4H: {
        defaultValue: "Adaptive Intelligence",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    onQtQXVcL4HChange: {
        changes: "QtQXVcL4H",
        type: ControlType.ChangeHandler
    },
    ScBCWp05W: {
        defaultValue: "Prospect learns how you work and adapts in real time. No retraining, no friction—just a system that evolves with your pace and priorities.",
        displayTextArea: false,
        title: "Text",
        type: ControlType.String
    },
    onScBCWp05WChange: {
        changes: "ScBCWp05W",
        type: ControlType.ChangeHandler
    }
});
addFonts(FramerzQZfnmNZX, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...ContentColorPatternFonts, ...getFontsFromSharedStyle(sharedStyle.fonts), ...getFontsFromSharedStyle(sharedStyle1.fonts)], {
    supportsExplicitInterCodegen: true
});
FramerzQZfnmNZX.loader = {
    load: (props, context) => {
        const locale = context.locale;
        return Promise.allSettled([forwardLoader(ContentColorPattern, {}, context)]);
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerzQZfnmNZX",
            "slots": [],
            "annotations": {
                "framerImmutableVariables": "true",
                "framerContractVersion": "1",
                "framerIntrinsicWidth": "296",
                "framerAutoSizeImages": "true",
                "framerComponentViewportWidth": "true",
                "framerDisplayContentsDiv": "false",
                "framerVariables": "{\"iYSCSMicO\":\"colorVersion\",\"QtQXVcL4H\":\"title\",\"ScBCWp05W\":\"text\"}",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"oIasTG3xn\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerIntrinsicHeight": "400",
                "framerColorSyntax": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./zQZfnmNZX.map