// Generated by Framer (747ab96)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    RichText,
    SVG,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/ZSxb90HIASvdWN4YA7om/cSb1K6k2iojMTLhOhN3d/nyfX5XJn8.js";
const cycleOrder = ["lFvlZ1aLT", "Q6e5yUI8q"];
const serializationHash = "framer-5mB9d";
const variantClassNames = {
    lFvlZ1aLT: "framer-v-jabb72",
    Q6e5yUI8q: "framer-v-zd9ost"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const Tf__rw21S = undefined;
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    Dark: "lFvlZ1aLT",
    Light: "Q6e5yUI8q"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    title,
    width,
    ...props
}) => {
    return { ...props,
        Tf__rw21S: title ? ? props.Tf__rw21S ? ? "Real-time dashboards",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "lFvlZ1aLT"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        Tf__rw21S,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "lFvlZ1aLT",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-jabb72", className, classNames),
                    "data-framer-name": "Dark",
                    layoutDependency: layoutDependency,
                    layoutId: "lFvlZ1aLT",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        Q6e5yUI8q: {
                            "data-framer-name": "Light"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1x0xcrv",
                        layoutDependency: layoutDependency,
                        layoutId: "oCqcXn2_J",
                        children: /*#__PURE__*/ _jsx(SVG, {
                            className: "framer-cmcbr2",
                            "data-framer-name": "Bullet",
                            layoutDependency: layoutDependency,
                            layoutId: "ZFsZ2IFRy",
                            radius: 25,
                            requiresOverflowVisible: false,
                            svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 6 6" overflow="visible"><path d="M 0 3 C 0 1.343 1.343 0 3 0 L 3 0 C 4.657 0 6 1.343 6 3 L 6 3 C 6 4.657 4.657 6 3 6 L 3 6 C 1.343 6 0 4.657 0 3 Z" fill="rgb(56, 56, 56)"></path></svg>',
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                Q6e5yUI8q: {
                                    svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 6 6" overflow="visible"><path d="M 0 3 C 0 1.343 1.343 0 3 0 L 3 0 C 4.657 0 6 1.343 6 3 L 6 3 C 6 4.657 4.657 6 3 6 L 3 6 C 1.343 6 0 4.657 0 3 Z" fill="rgb(254, 250, 243)"></path></svg>'
                                }
                            }, baseVariant, gestureVariant)
                        })
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-q53a36",
                                "data-styles-preset": "nyfX5XJn8",
                                dir: "auto",
                                children: "Real-time dashboards"
                            })
                        }),
                        className: "framer-1ueqnjo",
                        "data-framer-name": "Text",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "r_BQXi89z",
                        style: {
                            "--framer-paragraph-spacing": "0px"
                        },
                        text: Tf__rw21S,
                        variants: {
                            Q6e5yUI8q: {
                                "--extracted-r6o4lv": "var(--token-5c4b1449-c670-480a-8558-944f8cd8cf27, rgb(254, 250, 243))"
                            }
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            Q6e5yUI8q: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        className: "framer-styles-preset-q53a36",
                                        "data-styles-preset": "nyfX5XJn8",
                                        dir: "auto",
                                        style: {
                                            "--framer-text-color": "var(--extracted-r6o4lv, var(--token-5c4b1449-c670-480a-8558-944f8cd8cf27, rgb(254, 250, 243)))"
                                        },
                                        children: "Real-time dashboards"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-5mB9d.framer-tyunv0, .framer-5mB9d .framer-tyunv0 { display: block; }", ".framer-5mB9d.framer-jabb72 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 400px; }", ".framer-5mB9d .framer-1x0xcrv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: visible; padding: 7px 0px 0px 0px; position: relative; width: min-content; }", ".framer-5mB9d .framer-cmcbr2 { height: 6px; position: relative; width: 6px; }", ".framer-5mB9d .framer-1ueqnjo { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 22
 * @framerIntrinsicWidth 400
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"Q6e5yUI8q":{"layout":["fixed","auto"]}}}
 * @framerVariables {"Tf__rw21S":"title"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerCqW1PKEaY = withCSS(Component, css, "framer-5mB9d");
export default FramerCqW1PKEaY;
FramerCqW1PKEaY.displayName = "Plan Bullet 2";
FramerCqW1PKEaY.defaultProps = {
    height: 22,
    width: 400
};
addPropertyControls(FramerCqW1PKEaY, {
    variant: {
        options: ["lFvlZ1aLT", "Q6e5yUI8q"],
        optionTitles: ["Dark", "Light"],
        title: "Variant",
        type: ControlType.Enum
    },
    Tf__rw21S: {
        defaultValue: "Real-time dashboards",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    onTf__rw21SChange: {
        changes: "Tf__rw21S",
        type: ControlType.ChangeHandler
    }
});
addFonts(FramerCqW1PKEaY, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerCqW1PKEaY",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "400",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"Q6e5yUI8q\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerIntrinsicHeight": "22",
                "framerImmutableVariables": "true",
                "framerComponentViewportWidth": "true",
                "framerVariables": "{\"Tf__rw21S\":\"title\"}",
                "framerDisplayContentsDiv": "false",
                "framerAutoSizeImages": "true",
                "framerContractVersion": "1",
                "framerColorSyntax": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./CqW1PKEaY.map