// Generated by Framer (85eaff3)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    useSVGTemplate,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const mask = "var(--framer-icon-mask)";
const Base = /*#__PURE__*/ forwardRef(function(props, ref) {
    return /*#__PURE__*/ _jsx("svg", { ...props,
        ref: ref,
        children: props.children
    });
});
const MotionSVG = motion.create(Base);
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(MotionSVG, { ...rest,
        layoutId: layoutId,
        ref: ref,
        children: children
    }) : /*#__PURE__*/ _jsx("svg", { ...rest,
        ref: ref,
        children: children
    });
});
const svg = '<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 5 20 C 2.239 20 0 17.761 0 15 L 0 5 C 0 2.239 2.239 0 5 0 L 15 0 C 17.761 0 20 2.239 20 5 L 20 15 C 20 17.761 17.761 20 15 20 Z" fill="transparent" height="20px" id="WelWVC4aK" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(2 2)" width="20px"/><path d="M 7.957 3.413 C 8.21 5.12 7.34 6.797 5.798 7.573 C 4.257 8.349 2.392 8.049 1.172 6.829 C -0.049 5.608 -0.349 3.743 0.427 2.202 C 1.203 0.66 2.88 -0.21 4.587 0.043 C 6.33 0.302 7.698 1.67 7.957 3.413 Z" fill="transparent" height="8.000294809864354px" id="Y7WvVc7GI" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(8.043 7.957)" width="8.000294809864354px"/><path d="M 0 0 L 0.01 0" fill="transparent" height="1px" id="NoAMnmRyg" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(17.5 6.5)" width="1px"/></svg>';
const getProps = ({
    color,
    height,
    id,
    width,
    width1,
    ...props
}) => {
    return { ...props,
        JEeZYcamG: width1 ? ? props.JEeZYcamG ? ? 2,
        P_DcoRcrY: color ? ? props.P_DcoRcrY ? ? "rgb(0, 0, 0)"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        P_DcoRcrY,
        JEeZYcamG,
        ...restProps
    } = getProps(props);
    const href = useSVGTemplate("2988937525", svg);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-Tu4V5", className),
        layoutId: layoutId,
        ref: ref,
        role: "presentation",
        style: {
            "--1m973uw": P_DcoRcrY,
            "--js9iwy": JEeZYcamG,
            ...style
        },
        viewBox: "0 0 24 24",
        children: /*#__PURE__*/ _jsx("use", {
            href: href
        })
    });
});
const css = [`.framer-Tu4V5 { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"P_DcoRcrY":"color","JEeZYcamG":"width1"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Instagram","color":{"type":"variable","value":"1m973uw"},"set":{"localId":"vectorSet/ZsiCCGPvG","id":"ZsiCCGPvG","moduleId":"Y7SpbVH16cWqMhj75z1M"}}
 */
const Icon = withCSS(Component, css, "framer-Tu4V5");
Icon.displayName = "Instagram";
export default Icon;
addPropertyControls(Icon, {
    P_DcoRcrY: {
        defaultValue: "rgb(0, 0, 0)",
        hidden: false,
        title: "Color",
        type: ControlType.Color
    },
    JEeZYcamG: {
        defaultValue: 2,
        displayStepper: true,
        hidden: false,
        max: 16,
        min: 1,
        title: "Width",
        type: ControlType.Number
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerIntrinsicWidth": "24",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerIntrinsicHeight": "24",
                "framerVector": "{\"name\":\"Instagram\",\"color\":{\"type\":\"variable\",\"value\":\"1m973uw\"},\"set\":{\"localId\":\"vectorSet/ZsiCCGPvG\",\"id\":\"ZsiCCGPvG\",\"moduleId\":\"Y7SpbVH16cWqMhj75z1M\"}}",
                "framerVariables": "{\"P_DcoRcrY\":\"color\",\"JEeZYcamG\":\"width1\"}",
                "framerImmutableVariables": "true",
                "framerSupportedLayoutHeight": "any-prefer-fixed"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}