// Generated by Framer (7587b09)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = [".framer-lhgNe .framer-styles-preset-hye7x:not(.rich-text-wrapper), .framer-lhgNe .framer-styles-preset-hye7x.rich-text-wrapper a { --framer-link-hover-text-color: var(--token-e8aa88ef-13d6-420f-b9cf-d6a0f6bfd1a4, #d6d6d6); --framer-link-text-color: var(--token-0f516fd4-65c7-4b64-880e-09084b80b9c7, #ffffff); }"];
export const className = "framer-lhgNe";
export const __FramerMetadata__ = {
    "exports": {
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}