// Generated by Framer (bbed9c4)
export default function metadata(params, activeLocale) {
    return {
        description: "Echo is a Framer template built for sales intelligence and pipeline tools. Dark UI, scroll animations, pricing tables, testimonials, and a working contact form. Ready to publish.",
        favicon: "https://framerusercontent.com/assets/p0dgBQ6TP5CWy4kWqIPFl1ugo.png",
        robots: "max-image-preview:large",
        socialImage: "https://framerusercontent.com/assets/EjxGc86nDpzmR6KyfObJpa1xIFc.png",
        title: "Echo | SaaS Website Template"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}