// Generated by Framer (571faa6)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const mask = 'url(\'data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg"><path d="M 185.604 185.604 C 166.408 204.799 135.286 204.799 116.091 185.604 L 100 169.513 L 83.909 185.604 C 64.714 204.799 33.592 204.799 14.396 185.604 C -4.799 166.409 -4.799 135.287 14.396 116.091 L 30.488 100 L 14.397 83.909 C -4.798 64.714 -4.798 33.592 14.397 14.397 C 33.592 -4.799 64.714 -4.799 83.909 14.397 L 100 30.487 L 116.091 14.397 C 135.286 -4.799 166.408 -4.799 185.603 14.397 C 204.798 33.592 204.798 64.714 185.603 83.909 L 169.513 100 L 185.604 116.091 C 204.799 135.287 204.799 166.408 185.604 185.604 Z" fill="var(--1c2dmy6, rgb(0, 0, 0))" height="199.99976250000003px" id="lzAp035au" transform="translate(0 0)" width="200.00024750000003px"/></svg>\') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)';
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(motion.div, { ...rest,
        layoutId: layoutId,
        ref: ref
    }) : /*#__PURE__*/ _jsx("div", { ...rest,
        ref: ref
    });
});
const getProps = ({
    fill,
    height,
    id,
    width,
    width1,
    ...props
}) => {
    return { ...props,
        QmQcq56SU: fill ? ? props.QmQcq56SU ? ? "rgb(0, 0, 0)",
        rHwATwiyc: width1 ? ? props.rHwATwiyc ? ? 24
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        QmQcq56SU,
        rHwATwiyc,
        ...restProps
    } = getProps(props);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-IV1oF", className),
        layoutId: layoutId,
        ref: ref,
        style: {
            "--1c2dmy6": QmQcq56SU,
            ...style
        }
    });
});
const css = [`.framer-IV1oF { -webkit-mask: ${mask}; aspect-ratio: 1; background-color: var(--1c2dmy6); mask: ${mask}; width: 200px; }`];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 200
 * @framerIntrinsicHeight 200
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"QmQcq56SU":"fill","rHwATwiyc":"width1"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Shape  31","color":{"type":"variable","value":"1c2dmy6"},"set":{"localId":"vectorSet/gGHD6lwZ8","id":"gGHD6lwZ8","moduleId":"QHWg1wbjGIQLmMEdn4el"}}
 */
const Icon = withCSS(Component, css, "framer-IV1oF");
Icon.displayName = "Shape  31";
export default Icon;
addPropertyControls(Icon, {
    QmQcq56SU: {
        defaultValue: "rgb(0, 0, 0)",
        hidden: false,
        title: "Fill",
        type: ControlType.Color
    },
    rHwATwiyc: {
        defaultValue: 24,
        hidden: true,
        min: 0,
        title: "Width",
        type: ControlType.Number
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerSupportedLayoutHeight": "any-prefer-fixed",
                "framerVector": "{\"name\":\"Shape  31\",\"color\":{\"type\":\"variable\",\"value\":\"1c2dmy6\"},\"set\":{\"localId\":\"vectorSet/gGHD6lwZ8\",\"id\":\"gGHD6lwZ8\",\"moduleId\":\"QHWg1wbjGIQLmMEdn4el\"}}",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerIntrinsicHeight": "200",
                "framerIntrinsicWidth": "200",
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerVariables": "{\"QmQcq56SU\":\"fill\",\"rHwATwiyc\":\"width1\"}"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}