// Generated by Framer (7587b09)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    RichText,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/ygUs1FpB51WZwbYbKRfU/8lrom3UF8a5K5kLueBBT/wjtHCGvqq.js";
const cycleOrder = ["otjIrv9wS", "YX03s3s6w"];
const serializationHash = "framer-xF1lz";
const variantClassNames = {
    otjIrv9wS: "framer-v-zwvlvy",
    YX03s3s6w: "framer-v-ly57ow"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const eAHGXWjyh = undefined;
const mXpY5N3RA = undefined;
const transition1 = {
    duration: 0,
    type: "tween"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    Active: "YX03s3s6w",
    Default: "otjIrv9wS"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    click,
    height,
    id,
    title,
    width,
    ...props
}) => {
    return { ...props,
        eAHGXWjyh: click ? ? props.eAHGXWjyh,
        mXpY5N3RA: title ? ? props.mXpY5N3RA ? ? "Category",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "otjIrv9wS"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        mXpY5N3RA,
        eAHGXWjyh,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "otjIrv9wS",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTap1rkcrh4 = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (eAHGXWjyh) {
            const res = await eAHGXWjyh(...args);
            if (res === false) return false;
        }
    });
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-zwvlvy", className, classNames),
                    "data-framer-name": "Default",
                    "data-highlight": true,
                    layoutDependency: layoutDependency,
                    layoutId: "otjIrv9wS",
                    onTap: onTap1rkcrh4,
                    ref: refBinding,
                    style: {
                        backgroundColor: "rgba(187, 187, 187, 0.15)",
                        borderBottomLeftRadius: 8,
                        borderBottomRightRadius: 8,
                        borderTopLeftRadius: 8,
                        borderTopRightRadius: 8,
                        ...style
                    },
                    variants: {
                        YX03s3s6w: {
                            backgroundColor: "rgb(34, 34, 34)"
                        }
                    },
                    ...addPropertyOverrides({
                        YX03s3s6w: {
                            "data-framer-name": "Active"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-1icnjz7",
                                "data-styles-preset": "wjtHCGvqq",
                                dir: "auto",
                                children: "Category"
                            })
                        }),
                        className: "framer-mlghc6",
                        "data-framer-name": "Title",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "Josr4UWAa",
                        text: mXpY5N3RA,
                        variants: {
                            YX03s3s6w: {
                                "--extracted-r6o4lv": "rgb(255, 255, 255)"
                            }
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            YX03s3s6w: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        className: "framer-styles-preset-1icnjz7",
                                        "data-styles-preset": "wjtHCGvqq",
                                        dir: "auto",
                                        style: {
                                            "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))"
                                        },
                                        children: "Category"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-xF1lz.framer-1vg8slw, .framer-xF1lz .framer-1vg8slw { display: block; }", ".framer-xF1lz.framer-zwvlvy { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; padding: 12px; position: relative; width: min-content; }", ".framer-xF1lz .framer-mlghc6 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 41
 * @framerIntrinsicWidth 86.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"YX03s3s6w":{"layout":["auto","auto"]}}}
 * @framerVariables {"mXpY5N3RA":"title","eAHGXWjyh":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const Framerkexy4AdpL = withCSS(Component, css, "framer-xF1lz");
export default Framerkexy4AdpL;
Framerkexy4AdpL.displayName = "Tab";
Framerkexy4AdpL.defaultProps = {
    height: 41,
    width: 86.5
};
addPropertyControls(Framerkexy4AdpL, {
    variant: {
        options: ["otjIrv9wS", "YX03s3s6w"],
        optionTitles: ["Default", "Active"],
        title: "Variant",
        type: ControlType.Enum
    },
    mXpY5N3RA: {
        defaultValue: "Category",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    onmXpY5N3RAChange: {
        changes: "mXpY5N3RA",
        type: ControlType.ChangeHandler
    },
    eAHGXWjyh: {
        title: "Click",
        type: ControlType.EventHandler
    }
});
addFonts(Framerkexy4AdpL, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "Framerkexy4AdpL",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerAutoSizeImages": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"YX03s3s6w\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerVariables": "{\"mXpY5N3RA\":\"title\",\"eAHGXWjyh\":\"click\"}",
                "framerColorSyntax": "true",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicWidth": "86.5",
                "framerComponentViewportWidth": "true",
                "framerImmutableVariables": "true",
                "framerIntrinsicHeight": "41"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./kexy4AdpL.map