// Generated by Framer (bbed9c4)
import {
    fontStore
} from "framer";
fontStore.loadFonts(["GF;Stack Sans Headline-500", "GF;Stack Sans Headline-700"]);
export const fonts = [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Stack Sans Headline",
        openType: true,
        source: "google",
        style: "normal",
        uiFamilyName: "Stack Sans Headline",
        url: "https://fonts.gstatic.com/s/stacksansheadline/v1/1PtFg9jZXvmMnkLnuURbaukKZJTyrDV326uH6mSinjBIwc5fIgFCqgUA3ZCX.woff2",
        weight: "500"
    }, {
        cssFamilyName: "Stack Sans Headline",
        openType: true,
        source: "google",
        style: "normal",
        uiFamilyName: "Stack Sans Headline",
        url: "https://fonts.gstatic.com/s/stacksansheadline/v1/1PtFg9jZXvmMnkLnuURbaukKZJTyrDV326uH6mSinjBIwc6KJQFCqgUA3ZCX.woff2",
        weight: "700"
    }]
}];
export const css = [".framer-WDuT3 .framer-styles-preset-1ekcspu:not(.rich-text-wrapper), .framer-WDuT3 .framer-styles-preset-1ekcspu.rich-text-wrapper h4 { --framer-font-family: \"Stack Sans Headline\", \"Stack Sans Headline Placeholder\", sans-serif; --framer-font-family-bold: \"Stack Sans Headline\", \"Stack Sans Headline Placeholder\", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 28px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.01em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: #000000; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }"];
export const className = "framer-WDuT3";
export const __FramerMetadata__ = {
    "exports": {
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}