// Generated by Framer (3e39c08)
import {
    fontStore
} from "framer";
fontStore.loadFonts(["GF;Fragment Mono-regular", "GF;Fragment Mono-italic"]);
export const fonts = [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Fragment Mono",
        source: "google",
        style: "normal",
        uiFamilyName: "Fragment Mono",
        url: "https://fonts.gstatic.com/s/fragmentmono/v6/4iCr6K5wfMRRjxp0DA6-2CLnN4FNh4UI_1U.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Fragment Mono",
        source: "google",
        style: "italic",
        uiFamilyName: "Fragment Mono",
        url: "https://fonts.gstatic.com/s/fragmentmono/v6/4iC16K5wfMRRjxp0DA6-2CLnB4ZHhqcN71URtQ.woff2",
        weight: "400"
    }]
}];
export const css = ['.framer-GbTli .framer-styles-preset-fy7h5i:not(.rich-text-wrapper), .framer-GbTli .framer-styles-preset-fy7h5i.rich-text-wrapper p { --framer-font-family: "Fragment Mono", monospace; --framer-font-family-italic: "Fragment Mono", monospace; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-f6d71ca3-6af3-4d38-9676-ef999cc8b532, #232323); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }'];
export const className = "framer-GbTli";
export const __FramerMetadata__ = {
    "exports": {
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}