// Generated by Framer (7587b09)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import BackgroundPattern from "https://framerusercontent.com/modules/sbWEZhpbWDNQ64mRZcmT/Tf0ECRTfyblFDXnVL11a/Background_Pattern.js";
const BackgroundPatternFonts = getFonts(BackgroundPattern);
const cycleOrder = ["VhAdZ2ojK", "Kpz8UOaS9", "VoxYlBpoN", "OHtDswQo5", "EpmFPoKL_"];
const serializationHash = "framer-kHb5o";
const variantClassNames = {
    EpmFPoKL_: "framer-v-poy3x1",
    Kpz8UOaS9: "framer-v-1lhcikl",
    OHtDswQo5: "framer-v-jjb5ok",
    VhAdZ2ojK: "framer-v-teer2v",
    VoxYlBpoN: "framer-v-j3eufe"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    "Blue ": "Kpz8UOaS9",
    "Green ": "VoxYlBpoN",
    "Purple ": "VhAdZ2ojK",
    Orange: "OHtDswQo5",
    Yellow: "EpmFPoKL_"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "VhAdZ2ojK"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "VhAdZ2ojK",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-teer2v", className, classNames),
                    "data-framer-name": "Purple ",
                    layoutDependency: layoutDependency,
                    layoutId: "VhAdZ2ojK",
                    ref: refBinding,
                    style: {
                        backgroundColor: "var(--token-43ac2da6-43b0-4f5e-be9d-e096d7c8fa22, rgb(225, 193, 255))",
                        ...style
                    },
                    variants: {
                        EpmFPoKL_: {
                            backgroundColor: "var(--token-64add04c-b712-4b65-aff7-ed722857ae56, rgb(238, 255, 46))"
                        },
                        Kpz8UOaS9: {
                            backgroundColor: "var(--token-5cf71158-0f54-4ede-a5d1-4609fdcaa06b, rgb(143, 205, 255))"
                        },
                        OHtDswQo5: {
                            backgroundColor: "var(--token-abc4c04c-edf2-4ab8-a2a6-85fafc22936c, rgb(255, 197, 91))"
                        },
                        VoxYlBpoN: {
                            backgroundColor: "var(--token-5dfe5051-2420-4aef-8cca-35a4bb42745e, rgb(158, 230, 138))"
                        }
                    },
                    ...addPropertyOverrides({
                        EpmFPoKL_: {
                            "data-framer-name": "Yellow"
                        },
                        Kpz8UOaS9: {
                            "data-framer-name": "Blue "
                        },
                        OHtDswQo5: {
                            "data-framer-name": "Orange"
                        },
                        VoxYlBpoN: {
                            "data-framer-name": "Green "
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-1nxubo1-container",
                            isAuthoredByUser: true,
                            isModuleExternal: true,
                            layoutDependency: layoutDependency,
                            layoutId: "SVjzAazTU-container",
                            nodeId: "SVjzAazTU",
                            rendersWithMotion: true,
                            scopeId: "LUbgkKF68",
                            children: /*#__PURE__*/ _jsx(BackgroundPattern, {
                                backgroundColor: "rgba(0, 0, 0, 0)",
                                dotSize: 1.2,
                                fade: true,
                                fadeIntensity: 90,
                                fadeShape: "circle",
                                gap: 15,
                                height: "100%",
                                id: "SVjzAazTU",
                                layoutId: "SVjzAazTU",
                                patternColor: "rgb(71, 22, 161)",
                                patternOpacity: .4,
                                patternSize: 40,
                                patternType: "cross",
                                strokeWidth: 3,
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                width: "100%",
                                ...addPropertyOverrides({
                                    EpmFPoKL_: {
                                        patternColor: "rgb(85, 25, 140)",
                                        patternType: "texture"
                                    },
                                    Kpz8UOaS9: {
                                        patternColor: "rgb(41, 105, 145)",
                                        patternType: "xo"
                                    },
                                    OHtDswQo5: {
                                        patternColor: "rgb(138, 96, 18)",
                                        patternType: "signal"
                                    },
                                    VoxYlBpoN: {
                                        patternColor: "rgb(65, 133, 57)",
                                        patternOpacity: .3,
                                        patternSize: 20,
                                        patternType: "architect"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-kHb5o.framer-1rtxgyb, .framer-kHb5o .framer-1rtxgyb { display: block; }", ".framer-kHb5o.framer-teer2v { height: 120px; position: relative; width: 370px; }", ".framer-kHb5o .framer-1nxubo1-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 120
 * @framerIntrinsicWidth 370
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"Kpz8UOaS9":{"layout":["fixed","fixed"]},"VoxYlBpoN":{"layout":["fixed","fixed"]},"OHtDswQo5":{"layout":["fixed","fixed"]},"EpmFPoKL_":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerLUbgkKF68 = withCSS(Component, css, "framer-kHb5o");
export default FramerLUbgkKF68;
FramerLUbgkKF68.displayName = "Content / Color Pattern";
FramerLUbgkKF68.defaultProps = {
    height: 120,
    width: 370
};
addPropertyControls(FramerLUbgkKF68, {
    variant: {
        options: ["VhAdZ2ojK", "Kpz8UOaS9", "VoxYlBpoN", "OHtDswQo5", "EpmFPoKL_"],
        optionTitles: ["Purple ", "Blue ", "Green ", "Orange", "Yellow"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(FramerLUbgkKF68, [{
    explicitInter: true,
    fonts: []
}, ...BackgroundPatternFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerLUbgkKF68",
            "slots": [],
            "annotations": {
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicWidth": "370",
                "framerContractVersion": "1",
                "framerIntrinsicHeight": "120",
                "framerAutoSizeImages": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"Kpz8UOaS9\":{\"layout\":[\"fixed\",\"fixed\"]},\"VoxYlBpoN\":{\"layout\":[\"fixed\",\"fixed\"]},\"OHtDswQo5\":{\"layout\":[\"fixed\",\"fixed\"]},\"EpmFPoKL_\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerColorSyntax": "true",
                "framerImmutableVariables": "true",
                "framerComponentViewportWidth": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./LUbgkKF68.map