// Generated by Framer (747ab96)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getLoadingLazyAtYPosition,
    Image,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const serializationHash = "framer-tW4EV";
const variantClassNames = {
    vPHTLf4fA: "framer-v-1vmcled"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const LBtZvQD4a = undefined;
const toResponsiveImage = value => {
    if (typeof value === "object" && value !== null && typeof value.src === "string") {
        return value;
    }
    return typeof value === "string" ? {
        src: value
    } : undefined;
};
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    image,
    width,
    ...props
}) => {
    return { ...props,
        LBtZvQD4a: image ? ? props.LBtZvQD4a ? ? {
            pixelHeight: 1024,
            pixelWidth: 1024,
            src: "https://framerusercontent.com/images/WdTzs4h9TLc1RzMrpqDkFq4lY.png?width=1024&height=1024",
            srcSet: "https://framerusercontent.com/images/WdTzs4h9TLc1RzMrpqDkFq4lY.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/WdTzs4h9TLc1RzMrpqDkFq4lY.png?width=1024&height=1024 1024w"
        }
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        LBtZvQD4a,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "vPHTLf4fA",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Image, { ...restProps,
                    ...gestureHandlers,
                    background: {
                        alt: "",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(componentViewport ? .y || 0),
                        pixelHeight: 1024,
                        pixelWidth: 1024,
                        sizes: componentViewport ? .width || "100vw",
                        ...toResponsiveImage(LBtZvQD4a)
                    },
                    className: cx(scopingClassNames, "framer-1vmcled", className, classNames),
                    "data-border": true,
                    "data-framer-name": "Default",
                    layoutDependency: layoutDependency,
                    layoutId: "vPHTLf4fA",
                    ref: refBinding,
                    style: {
                        "--border-bottom-width": "1px",
                        "--border-color": "rgba(47, 44, 37, 0.12)",
                        "--border-left-width": "1px",
                        "--border-right-width": "1px",
                        "--border-style": "solid",
                        "--border-top-width": "1px",
                        backdropFilter: "blur(14px)",
                        borderBottomLeftRadius: 200,
                        borderBottomRightRadius: 200,
                        borderTopLeftRadius: 200,
                        borderTopRightRadius: 200,
                        boxShadow: "0px 4px 18px 0px rgba(0, 0, 0, 0.12)",
                        WebkitBackdropFilter: "blur(14px)",
                        ...style
                    }
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-tW4EV.framer-h6nf3g, .framer-tW4EV .framer-h6nf3g { display: block; }", ".framer-tW4EV.framer-1vmcled { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 72px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 72px; }", '.framer-tW4EV[data-border="true"]::after, .framer-tW4EV [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 72
 * @framerIntrinsicWidth 72
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"LBtZvQD4a":"image"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerbWCeea7Vn = withCSS(Component, css, "framer-tW4EV");
export default FramerbWCeea7Vn;
FramerbWCeea7Vn.displayName = "Avatar";
FramerbWCeea7Vn.defaultProps = {
    height: 72,
    width: 72
};
addPropertyControls(FramerbWCeea7Vn, {
    LBtZvQD4a: {
        __defaultAssetReference: "data:framer/asset-reference,WdTzs4h9TLc1RzMrpqDkFq4lY.png?originalFilename=photo-avatars-3.png&width=1024&height=1024",
        title: "Image",
        type: ControlType.ResponsiveImage
    }
});
addFonts(FramerbWCeea7Vn, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerbWCeea7Vn",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerDisplayContentsDiv": "false",
                "framerComponentViewportWidth": "true",
                "framerAutoSizeImages": "true",
                "framerColorSyntax": "true",
                "framerVariables": "{\"LBtZvQD4a\":\"image\"}",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "72",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerIntrinsicHeight": "72"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./bWCeea7Vn.map