// Generated by Framer (85eaff3)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    useSVGTemplate,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const mask = "var(--framer-icon-mask)";
const Base = /*#__PURE__*/ forwardRef(function(props, ref) {
    return /*#__PURE__*/ _jsx("svg", { ...props,
        ref: ref,
        children: props.children
    });
});
const MotionSVG = motion.create(Base);
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(MotionSVG, { ...rest,
        layoutId: layoutId,
        ref: ref,
        children: children
    }) : /*#__PURE__*/ _jsx("svg", { ...rest,
        ref: ref,
        children: children
    });
});
const svg = '<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 11 0 L 8 0 C 5.239 0 3 2.239 3 5 L 3 8 L 0 8 L 0 12 L 3 12 L 3 20 L 7 20 L 7 12 L 10 12 L 11 8 L 7 8 L 7 5 C 7 4.448 7.448 4 8 4 L 11 4 Z" fill="transparent" height="20px" id="F9iMxikzW" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(7 2)" width="11px"/></svg>';
const getProps = ({
    color,
    height,
    id,
    width,
    width1,
    ...props
}) => {
    return { ...props,
        JEeZYcamG: width1 ? ? props.JEeZYcamG ? ? 2,
        P_DcoRcrY: color ? ? props.P_DcoRcrY ? ? "rgb(0, 0, 0)"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        P_DcoRcrY,
        JEeZYcamG,
        ...restProps
    } = getProps(props);
    const href = useSVGTemplate("3191071638", svg);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-5MaOE", className),
        layoutId: layoutId,
        ref: ref,
        role: "presentation",
        style: {
            "--1m973uw": P_DcoRcrY,
            "--js9iwy": JEeZYcamG,
            ...style
        },
        viewBox: "0 0 24 24",
        children: /*#__PURE__*/ _jsx("use", {
            href: href
        })
    });
});
const css = [`.framer-5MaOE { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"P_DcoRcrY":"color","JEeZYcamG":"width1"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Facebook","color":{"type":"variable","value":"1m973uw"},"set":{"localId":"vectorSet/ZsiCCGPvG","id":"ZsiCCGPvG","moduleId":"Y7SpbVH16cWqMhj75z1M"}}
 */
const Icon = withCSS(Component, css, "framer-5MaOE");
Icon.displayName = "Facebook";
export default Icon;
addPropertyControls(Icon, {
    P_DcoRcrY: {
        defaultValue: "rgb(0, 0, 0)",
        hidden: false,
        title: "Color",
        type: ControlType.Color
    },
    JEeZYcamG: {
        defaultValue: 2,
        displayStepper: true,
        hidden: false,
        max: 16,
        min: 1,
        title: "Width",
        type: ControlType.Number
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerVector": "{\"name\":\"Facebook\",\"color\":{\"type\":\"variable\",\"value\":\"1m973uw\"},\"set\":{\"localId\":\"vectorSet/ZsiCCGPvG\",\"id\":\"ZsiCCGPvG\",\"moduleId\":\"Y7SpbVH16cWqMhj75z1M\"}}",
                "framerIntrinsicHeight": "24",
                "framerVariables": "{\"P_DcoRcrY\":\"color\",\"JEeZYcamG\":\"width1\"}",
                "framerSupportedLayoutHeight": "any-prefer-fixed",
                "framerContractVersion": "1",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "24"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}