// Generated by Framer (07ac007)
import siteMetadata from "#framer/local/siteMetadata/siteMetadata/siteMetadata.js";
export default function metadata(params, activeLocale) {
    return {
        breakpoints: [{
            hash: "196vosk",
            mediaQuery: "(min-width: 1200px)"
        }, {
            hash: "1i87fhb",
            mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"
        }, {
            hash: "19qy3s4",
            mediaQuery: "(max-width: 809.98px)"
        }],
        description: siteMetadata(params, activeLocale).description,
        elements: {
            W6diUGlgy: "scrolltrigger"
        },
        robots: "max-image-preview:large",
        serializationId: "framer-Tqfby",
        title: siteMetadata(params, activeLocale).title || "Get Started",
        viewport: "width=device-width"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}