// Generated by Framer (7587b09)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    Instance,
    Link,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import Instagram from "https://framerusercontent.com/modules/MatTltl54L7WHNXwSZ0c/tqevvT2hO3o1AMLi2ckU/SP4n0DCbm.js";
const enabledGestures = {
    EOQ3ZLe5D: {
        hover: true
    }
};
const serializationHash = "framer-KyTjk";
const variantClassNames = {
    EOQ3ZLe5D: "framer-v-vew7tw"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const mo3CZ5UCQ = undefined;
const rPeCrRxut = undefined;
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    icon,
    id,
    link,
    width,
    ...props
}) => {
    return { ...props,
        mo3CZ5UCQ: link ? ? props.mo3CZ5UCQ,
        rPeCrRxut: icon ? ? props.rPeCrRxut ? ? Instagram
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        rPeCrRxut,
        mo3CZ5UCQ,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "EOQ3ZLe5D",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: mo3CZ5UCQ,
                    motionChild: true,
                    nodeId: "EOQ3ZLe5D",
                    openInNewTab: false,
                    scopeId: "KbFSWLs67",
                    children: /*#__PURE__*/ _jsx(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-vew7tw",className,classNames)} framer-l24von`,
                        "data-framer-name": "Variant 1",
                        layoutDependency: layoutDependency,
                        layoutId: "EOQ3ZLe5D",
                        ref: refBinding,
                        style: {
                            backgroundColor: "rgba(247, 247, 247, 0.56)",
                            borderBottomLeftRadius: 6,
                            borderBottomRightRadius: 6,
                            borderTopLeftRadius: 6,
                            borderTopRightRadius: 6,
                            ...style
                        },
                        variants: {
                            "EOQ3ZLe5D-hover": {
                                backgroundColor: "var(--token-847720cf-a3a9-4922-bb4c-bbba010634be, rgb(247, 247, 247))"
                            }
                        },
                        ...addPropertyOverrides({
                            "EOQ3ZLe5D-hover": {
                                "data-framer-name": undefined
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(Instance, {
                            animated: true,
                            className: "framer-ujganv",
                            Component: rPeCrRxut,
                            layoutDependency: layoutDependency,
                            layoutId: "CQLsidl4s",
                            style: {
                                "--1m973uw": "var(--token-c1f30440-96cf-4826-9022-8bb46c0cd1a3, rgb(35, 35, 35))",
                                "--js9iwy": 1.8
                            }
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-KyTjk.framer-l24von, .framer-KyTjk .framer-l24von { display: block; }", ".framer-KyTjk.framer-vew7tw { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: visible; padding: 6px; position: relative; text-decoration: none; width: min-content; }", ".framer-KyTjk .framer-ujganv { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 21px); position: relative; width: 20px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 32
 * @framerIntrinsicWidth 32
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"PBGJRtbgU":{"layout":["auto","auto"]}}}
 * @framerVariables {"rPeCrRxut":"icon","mo3CZ5UCQ":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerVectorSets ["Y7SpbVH16cWqMhj75z1M"]
 */
const FramerKbFSWLs67 = withCSS(Component, css, "framer-KyTjk");
export default FramerKbFSWLs67;
FramerKbFSWLs67.displayName = "Social Button";
FramerKbFSWLs67.defaultProps = {
    height: 32,
    width: 32
};
addPropertyControls(FramerKbFSWLs67, {
    rPeCrRxut: {
        defaultValue: {
            identifier: "module:MatTltl54L7WHNXwSZ0c/tqevvT2hO3o1AMLi2ckU/SP4n0DCbm.js:default",
            moduleId: "MatTltl54L7WHNXwSZ0c"
        },
        setModuleId: "Y7SpbVH16cWqMhj75z1M",
        title: "Icon",
        type: ControlType.VectorSetItem
    },
    mo3CZ5UCQ: {
        title: "Link",
        type: ControlType.Link
    }
});
addFonts(FramerKbFSWLs67, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerKbFSWLs67",
            "slots": [],
            "annotations": {
                "framerImmutableVariables": "true",
                "framerContractVersion": "1",
                "framerComponentViewportWidth": "true",
                "framerIntrinsicWidth": "32",
                "framerColorSyntax": "true",
                "framerVectorSets": "[\"Y7SpbVH16cWqMhj75z1M\"]",
                "framerVariables": "{\"rPeCrRxut\":\"icon\",\"mo3CZ5UCQ\":\"link\"}",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicHeight": "32",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"PBGJRtbgU\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerAutoSizeImages": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./KbFSWLs67.map