// Generated by Framer (ea22747)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    forwardLoader,
    getFonts,
    getFontsFromSharedStyle,
    RichText,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS,
    withFX
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/uhp6Sps2B7owixhQDPsI/t0JMJdJjpqgvJyb5ruzB/G93coWMC_.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/2MDIiUBS7gGkHRvVt6x7/INSzMncUdaFAj7bOs9bd/wP6sQiFFO.js";
import PrimaryButton from "https://framerusercontent.com/modules/N0jJvKc7oznuAyabsWTg/0w9ACL4bFhDgwwGWg3sB/n5HUm6Rxu.js";
const RichTextWithFX = withFX(RichText);
const PrimaryButtonFonts = getFonts(PrimaryButton);
const serializationHash = "framer-QTr6B";
const variantClassNames = {
    A9Pubnlb4: "framer-v-1b9k11h"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const HHw47XrFP = undefined;
const GHmEssbe9 = undefined;
const uKuhJWGbk = undefined;
const uuHTYbGzG = undefined;
const iu2nHwJLF = undefined;
const setuuHTYbGzG = undefined;
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const animation = {
    opacity: 0,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: 20
};
const transition2 = {
    bounce: .2,
    delay: .1,
    duration: .6,
    type: "spring"
};
const transition3 = {
    bounce: .2,
    delay: .1,
    duration: .5,
    type: "spring"
};
const matchVariant = (...args) => {
    for (const arg of args) {
        if (arg && typeof arg === "string") return arg;
    }
    return undefined;
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const useStateVariable = (externalState, setExternalState) => {
    const [internalState, setInternalState] = React.useState(externalState);
    const [previousExternalState, setPreviousExternalState] = React.useState(externalState);
    if (setExternalState) {
        return [externalState, setExternalState];
    }
    if (externalState !== previousExternalState) {
        setInternalState(externalState);
        setPreviousExternalState(externalState);
    }
    return [internalState, setInternalState];
};
const getProps = ({
    body,
    button,
    buttonLink,
    buttonText,
    height,
    id,
    title,
    width,
    ...props
}) => {
    return { ...props,
        GHmEssbe9: body ? ? props.GHmEssbe9 ? ? "This is where you place the body copy, which can be a bit longer. However, no long novels please.",
        HHw47XrFP: title ? ? props.HHw47XrFP ? ? "An engaging title",
        iu2nHwJLF: buttonLink ? ? props.iu2nHwJLF,
        uKuhJWGbk: button ? ? props.uKuhJWGbk,
        uuHTYbGzG: buttonText ? ? props.uuHTYbGzG ? ? "Explore"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        HHw47XrFP,
        GHmEssbe9,
        uKuhJWGbk,
        "uuHTYbGzG": externaluuHTYbGzG,
        "onuuHTYbGzGChange": setExternaluuHTYbGzG,
        iu2nHwJLF,
        ...restProps
    } = getProps(props);
    const [uuHTYbGzG, setuuHTYbGzG] = useStateVariable(externaluuHTYbGzG, setExternaluuHTYbGzG);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "A9Pubnlb4",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1b9k11h", className, classNames),
                    "data-framer-name": "Variant 1",
                    layoutDependency: layoutDependency,
                    layoutId: "A9Pubnlb4",
                    ref: refBinding,
                    style: { ...style
                    },
                    children: [ /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1c950u1",
                        "data-framer-name": "Text",
                        layoutDependency: layoutDependency,
                        layoutId: "AbKZ6d_5I",
                        children: /*#__PURE__*/ _jsxs(motion.div, {
                            className: "framer-14aiv6j",
                            "data-framer-name": "Content",
                            layoutDependency: layoutDependency,
                            layoutId: "n_Uphxob_",
                            children: [ /*#__PURE__*/ _jsx(RichTextWithFX, {
                                __framer__animate: {
                                    transition: transition2
                                },
                                __framer__animateOnce: true,
                                __framer__enter: animation,
                                __framer__styleAppearEffectEnabled: true,
                                __framer__threshold: .5,
                                __fromCanvasComponent: true,
                                __perspectiveFX: false,
                                __smartComponentFX: true,
                                __targetOpacity: 1,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.h3, {
                                        className: "framer-styles-preset-7c3tn1",
                                        "data-styles-preset": "G93coWMC_",
                                        dir: "auto",
                                        children: "An engaging title"
                                    })
                                }),
                                className: "framer-xxw6b8",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "sZv6VBg7_",
                                style: {
                                    "--framer-link-text-color": "rgb(0, 153, 255)",
                                    "--framer-link-text-decoration": "underline"
                                },
                                text: HHw47XrFP,
                                verticalAlignment: "top",
                                withExternalLayout: true
                            }), /*#__PURE__*/ _jsx(RichTextWithFX, {
                                __framer__animate: {
                                    transition: transition3
                                },
                                __framer__animateOnce: true,
                                __framer__enter: animation,
                                __framer__styleAppearEffectEnabled: true,
                                __framer__threshold: .5,
                                __fromCanvasComponent: true,
                                __perspectiveFX: false,
                                __smartComponentFX: true,
                                __targetOpacity: 1,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        className: "framer-styles-preset-mja16w",
                                        "data-styles-preset": "wP6sQiFFO",
                                        dir: "auto",
                                        children: "This is where you place the body copy, which can be a bit longer. However, no long novels please."
                                    })
                                }),
                                className: "framer-vm4d9q",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "bRBe0n3XX",
                                style: {
                                    "--framer-link-text-color": "rgb(0, 153, 255)",
                                    "--framer-link-text-decoration": "underline"
                                },
                                text: GHmEssbe9,
                                verticalAlignment: "top",
                                withExternalLayout: true
                            })]
                        })
                    }), /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-eqqpm6",
                        "data-framer-name": "Buttons",
                        layoutDependency: layoutDependency,
                        layoutId: "uz9r5oeRg",
                        children: uKuhJWGbk !== false && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 51,
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-138fu7l-container",
                                layoutDependency: layoutDependency,
                                layoutId: "Q9aSd7lQ3-container",
                                nodeId: "Q9aSd7lQ3",
                                rendersWithMotion: true,
                                scopeId: "cHTzNagvQ",
                                children: /*#__PURE__*/ _jsx(PrimaryButton, {
                                    bazhcxY6s: uuHTYbGzG,
                                    height: "100%",
                                    id: "Q9aSd7lQ3",
                                    layoutId: "Q9aSd7lQ3",
                                    onbazhcxY6sChange: setuuHTYbGzG,
                                    SYP7WArYx: iu2nHwJLF,
                                    U9GTEeL_y: true,
                                    variant: matchVariant("i4pKhRM_A"),
                                    width: "100%"
                                })
                            })
                        })
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-QTr6B.framer-x59oo1, .framer-QTr6B .framer-x59oo1 { display: block; }", ".framer-QTr6B.framer-1b9k11h { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; max-width: 400px; overflow: visible; padding: 0px; position: relative; width: 400px; }", ".framer-QTr6B .framer-1c950u1 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }", ".framer-QTr6B .framer-14aiv6j { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }", ".framer-QTr6B .framer-xxw6b8, .framer-QTr6B .framer-vm4d9q { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }", ".framer-QTr6B .framer-eqqpm6 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }", ".framer-QTr6B .framer-138fu7l-container { flex: none; height: auto; position: relative; width: auto; }", ...sharedStyle.css, ...sharedStyle1.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 223
 * @framerIntrinsicWidth 400
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"],"constraints":[null,"400px",null,null]}}}
 * @framerVariables {"HHw47XrFP":"title","GHmEssbe9":"body","uKuhJWGbk":"button","uuHTYbGzG":"buttonText","iu2nHwJLF":"buttonLink"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramercHTzNagvQ = withCSS(Component, css, "framer-QTr6B");
export default FramercHTzNagvQ;
FramercHTzNagvQ.displayName = "Scroll Content";
FramercHTzNagvQ.defaultProps = {
    height: 223,
    width: 400
};
addPropertyControls(FramercHTzNagvQ, {
    HHw47XrFP: {
        defaultValue: "An engaging title",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    onHHw47XrFPChange: {
        changes: "HHw47XrFP",
        type: ControlType.ChangeHandler
    },
    GHmEssbe9: {
        defaultValue: "This is where you place the body copy, which can be a bit longer. However, no long novels please.",
        displayTextArea: false,
        title: "Body",
        type: ControlType.String
    },
    onGHmEssbe9Change: {
        changes: "GHmEssbe9",
        type: ControlType.ChangeHandler
    },
    uKuhJWGbk: {
        optional: true,
        title: "Button?",
        type: ControlType.Boolean
    },
    onuKuhJWGbkChange: {
        changes: "uKuhJWGbk",
        type: ControlType.ChangeHandler
    },
    uuHTYbGzG: {
        defaultValue: "Explore",
        displayTextArea: false,
        title: "Button Text",
        type: ControlType.String
    },
    onuuHTYbGzGChange: {
        changes: "uuHTYbGzG",
        type: ControlType.ChangeHandler
    },
    iu2nHwJLF: {
        title: "Button Link",
        type: ControlType.Link
    }
});
addFonts(FramercHTzNagvQ, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...PrimaryButtonFonts, ...getFontsFromSharedStyle(sharedStyle.fonts), ...getFontsFromSharedStyle(sharedStyle1.fonts)], {
    supportsExplicitInterCodegen: true
});
FramercHTzNagvQ.loader = {
    load: (props, context) => {
        const locale = context.locale;
        return Promise.allSettled([forwardLoader(PrimaryButton, {}, context)]);
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramercHTzNagvQ",
            "slots": [],
            "annotations": {
                "framerAutoSizeImages": "true",
                "framerVariables": "{\"HHw47XrFP\":\"title\",\"GHmEssbe9\":\"body\",\"uKuhJWGbk\":\"button\",\"uuHTYbGzG\":\"buttonText\",\"iu2nHwJLF\":\"buttonLink\"}",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"],\"constraints\":[null,\"400px\",null,null]}}}",
                "framerIntrinsicWidth": "400",
                "framerContractVersion": "1",
                "framerDisplayContentsDiv": "false",
                "framerColorSyntax": "true",
                "framerIntrinsicHeight": "223",
                "framerImmutableVariables": "true",
                "framerComponentViewportWidth": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./cHTzNagvQ.map