// Generated by Framer (747ab96)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    cx,
    motion,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const mask = 'url(\'data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 291 122" xmlns="http://www.w3.org/2000/svg"><path d="M 0 54.203 C 56.585 133.465 80.93 112.922 99.5 80.864 C 118.07 48.805 130.863 5.232 165 0.364 C 241.426 -7.472 229.304 114.093 291.292 89.703" fill="transparent" height="109.31051283137504px" id="bCHWcd9HN" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="miter" stroke-miterlimit="10" stroke-width="1.8" stroke="var(--token-8c2490e6-553f-4b78-874c-6b3f130509d6, rgb(158, 230, 138))" transform="translate(0 9.136)" width="291.2916669845581px"/></svg>\') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)';
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(motion.div, { ...rest,
        layoutId: layoutId,
        ref: ref
    }) : /*#__PURE__*/ _jsx("div", { ...rest,
        ref: ref
    });
});
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-q5pZC", className),
        layoutId: layoutId,
        ref: ref,
        style: { ...style
        }
    });
});
const css = [`.framer-q5pZC { -webkit-mask: ${mask}; aspect-ratio: 2.3852459016393444; background-color: var(--token-8c2490e6-553f-4b78-874c-6b3f130509d6, #9ee68a); mask: ${mask}; width: 291px; }`];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 291
 * @framerIntrinsicHeight 122
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerImmutableVariables true
 * @framerVector {"name":"Vector","color":{"type":"static","value":"var(--token-8c2490e6-553f-4b78-874c-6b3f130509d6, rgb(158, 230, 138))"},"set":{"localId":"vectorSet/U3zb1Ydgb","id":"U3zb1Ydgb","moduleId":"FPk0IIpJRtec8CojxJiT"}}
 */
const Icon = withCSS(Component, css, "framer-q5pZC");
Icon.displayName = "Vector";
export default Icon;
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "291",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerVector": "{\"name\":\"Vector\",\"color\":{\"type\":\"static\",\"value\":\"var(--token-8c2490e6-553f-4b78-874c-6b3f130509d6, rgb(158, 230, 138))\"},\"set\":{\"localId\":\"vectorSet/U3zb1Ydgb\",\"id\":\"U3zb1Ydgb\",\"moduleId\":\"FPk0IIpJRtec8CojxJiT\"}}",
                "framerSupportedLayoutHeight": "any-prefer-fixed",
                "framerIntrinsicHeight": "122",
                "framerContractVersion": "1",
                "framerImmutableVariables": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}