// Generated by Framer (bbed9c4)
import {
    fontStore
} from "framer";
fontStore.loadFonts(["GF;Stack Sans Text-500", "GF;Stack Sans Text-700"]);
export const fonts = [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Stack Sans Text",
        openType: true,
        source: "google",
        style: "normal",
        uiFamilyName: "Stack Sans Text",
        url: "https://fonts.gstatic.com/s/stacksanstext/v1/kJEkBuAJ-Q0hiGPmzHEu345X1JJNBpRJ3RPan47MNj2KJOhyGgKF1a0.woff2",
        weight: "500"
    }, {
        cssFamilyName: "Stack Sans Text",
        openType: true,
        source: "google",
        style: "normal",
        uiFamilyName: "Stack Sans Text",
        url: "https://fonts.gstatic.com/s/stacksanstext/v1/kJEkBuAJ-Q0hiGPmzHEu345X1JJNBpRJ3RPan47MNuiNJOhyGgKF1a0.woff2",
        weight: "700"
    }]
}];
export const css = [".framer-M2NBu .framer-styles-preset-1icnjz7:not(.rich-text-wrapper), .framer-M2NBu .framer-styles-preset-1icnjz7.rich-text-wrapper p { --framer-font-family: \"Stack Sans Text\", \"Stack Sans Text Placeholder\", sans-serif; --framer-font-family-bold: \"Stack Sans Text\", \"Stack Sans Text Placeholder\", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: #666666; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }"];
export const className = "framer-M2NBu";
export const __FramerMetadata__ = {
    "exports": {
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}