// Generated by Framer (07ac007)
import siteMetadata from "#framer/local/siteMetadata/siteMetadata/siteMetadata.js";
export default function metadata(params, activeLocale) {
    return {
        breakpoints: [{
            hash: "1cndp1j",
            mediaQuery: "(min-width: 1200px)"
        }, {
            hash: "c64k2x",
            mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"
        }, {
            hash: "13hz73a",
            mediaQuery: "(max-width: 809.98px)"
        }],
        description: siteMetadata(params, activeLocale).description,
        elements: {
            Ag3xqCk5V: "about-b",
            BEJTivwRj: "about-c",
            ecLAPttth: "features-2",
            fIpXrQgdW: "about-a",
            nkY1MJ4Wr: "pricing",
            oCdcFNpUt: "faq",
            PN76nB37I: "scrolltrigger",
            YnH7SkttP: "features",
            yXw15szUH: "testimonials",
            z_m4ySwqd: "about"
        },
        robots: "max-image-preview:large",
        serializationId: "framer-lhxqk",
        title: siteMetadata(params, activeLocale).title || "Home",
        viewport: "width=device-width"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}