// Generated by Framer (7587b09)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    Link,
    RichText,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/LvAWLVEhRrPlPC87B91s/rCC1WclxQuC02yMPqpic/Ly6AUOa0V.js";
const serializationHash = "framer-CvCEx";
const variantClassNames = {
    o3MWGe51H: "framer-v-1t85vol"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const YcwQIIMVe = undefined;
const BFhC6pNFP = undefined;
const UhC4sW8Gf = undefined;
const gXnn4SgRT = undefined;
const transition1 = {
    delay: 0,
    duration: .05,
    ease: [.12, .23, .5, 1],
    type: "tween"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    closeMenu,
    height,
    id,
    link,
    newTab,
    pageTitle,
    width,
    ...props
}) => {
    return { ...props,
        BFhC6pNFP: link ? ? props.BFhC6pNFP,
        gXnn4SgRT: pageTitle ? ? props.gXnn4SgRT ? ? "Page title",
        UhC4sW8Gf: newTab ? ? props.UhC4sW8Gf ? ? true,
        YcwQIIMVe: closeMenu ? ? props.YcwQIIMVe
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        gXnn4SgRT,
        BFhC6pNFP,
        UhC4sW8Gf,
        YcwQIIMVe,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "o3MWGe51H",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTapfjy8ma = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (YcwQIIMVe) {
            const res = await YcwQIIMVe(...args);
            if (res === false) return false;
        }
    });
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: BFhC6pNFP,
                    motionChild: true,
                    nodeId: "o3MWGe51H",
                    openInNewTab: UhC4sW8Gf,
                    scopeId: "q65ufUKPh",
                    children: /*#__PURE__*/ _jsx(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-1t85vol",className,classNames)} framer-1g4i7xd`,
                        "data-framer-name": "Default",
                        "data-highlight": true,
                        layoutDependency: layoutDependency,
                        layoutId: "o3MWGe51H",
                        onTap: onTapfjy8ma,
                        ref: refBinding,
                        style: {
                            backgroundColor: "var(--token-2561606a-ce95-4f1d-9927-306123c4cdd2, rgba(255, 255, 255, 0))",
                            borderBottomLeftRadius: 16,
                            borderBottomRightRadius: 16,
                            borderTopLeftRadius: 16,
                            borderTopRightRadius: 16,
                            ...style
                        },
                        children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-sm0w79",
                                    "data-styles-preset": "Ly6AUOa0V",
                                    dir: "auto",
                                    children: "Page title"
                                })
                            }),
                            className: "framer-1bpmdp4",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "ZAVFlchHD",
                            style: {
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline"
                            },
                            text: gXnn4SgRT,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-CvCEx.framer-1g4i7xd, .framer-CvCEx .framer-1g4i7xd { display: block; }", ".framer-CvCEx.framer-1t85vol { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }", ".framer-CvCEx .framer-1bpmdp4 { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 100
 * @framerIntrinsicWidth 382
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerVariables {"gXnn4SgRT":"pageTitle","BFhC6pNFP":"link","UhC4sW8Gf":"newTab","YcwQIIMVe":"closeMenu"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const Framerq65ufUKPh = withCSS(Component, css, "framer-CvCEx");
export default Framerq65ufUKPh;
Framerq65ufUKPh.displayName = "Nav Item Phone";
Framerq65ufUKPh.defaultProps = {
    height: 100,
    width: 382
};
addPropertyControls(Framerq65ufUKPh, {
    gXnn4SgRT: {
        defaultValue: "Page title",
        displayTextArea: false,
        title: "Page title",
        type: ControlType.String
    },
    ongXnn4SgRTChange: {
        changes: "gXnn4SgRT",
        type: ControlType.ChangeHandler
    },
    BFhC6pNFP: {
        title: "Link",
        type: ControlType.Link
    },
    UhC4sW8Gf: {
        defaultValue: true,
        title: "↳ New Tab",
        type: ControlType.Boolean
    },
    onUhC4sW8GfChange: {
        changes: "UhC4sW8Gf",
        type: ControlType.ChangeHandler
    },
    YcwQIIMVe: {
        title: "Close Menu",
        type: ControlType.EventHandler
    }
});
addFonts(Framerq65ufUKPh, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Framerq65ufUKPh",
            "slots": [],
            "annotations": {
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicHeight": "100",
                "framerImmutableVariables": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerIntrinsicWidth": "382",
                "framerContractVersion": "1",
                "framerAutoSizeImages": "true",
                "framerColorSyntax": "true",
                "framerComponentViewportWidth": "true",
                "framerVariables": "{\"gXnn4SgRT\":\"pageTitle\",\"BFhC6pNFP\":\"link\",\"UhC4sW8Gf\":\"newTab\",\"YcwQIIMVe\":\"closeMenu\"}"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}