// Generated by Framer (85eaff3)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    useSVGTemplate,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const mask = "var(--framer-icon-mask)";
const Base = /*#__PURE__*/ forwardRef(function(props, ref) {
    return /*#__PURE__*/ _jsx("svg", { ...props,
        ref: ref,
        children: props.children
    });
});
const MotionSVG = motion.create(Base);
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(MotionSVG, { ...rest,
        layoutId: layoutId,
        ref: ref,
        children: children
    }) : /*#__PURE__*/ _jsx("svg", { ...rest,
        ref: ref,
        children: children
    });
});
const svg = '<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 9.019 0.816 C 9.108 0.343 9.521 0 10.002 0 C 10.484 0 10.897 0.343 10.985 0.816 L 12.036 6.374 C 12.189 7.183 12.822 7.816 13.63 7.968 L 19.188 9.019 C 19.662 9.108 20.005 9.521 20.005 10.002 C 20.005 10.484 19.662 10.897 19.188 10.985 L 13.63 12.036 C 12.822 12.189 12.189 12.822 12.036 13.63 L 10.985 19.188 C 10.897 19.662 10.484 20.005 10.002 20.005 C 9.521 20.005 9.108 19.662 9.019 19.188 L 7.968 13.63 C 7.816 12.822 7.183 12.189 6.374 12.036 L 0.816 10.985 C 0.343 10.897 0 10.484 0 10.002 C 0 9.521 0.343 9.108 0.816 9.019 L 6.374 7.968 C 7.183 7.816 7.816 7.183 7.968 6.374 Z" fill="transparent" height="20.004788889056996px" id="r3ITwxBG7" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(1.998 1.998)" width="20.004788889056993px"/><path d="M 0 0 L 0 4" fill="transparent" height="4px" id="npiFUOZYL" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(20 2)" width="1px"/><path d="M 4 0 L 0 0" fill="transparent" height="1px" id="KnnF_NlKv" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(18 4)" width="4px"/><path d="M 0 2 C 0 0.895 0.895 0 2 0 C 3.105 0 4 0.895 4 2 C 4 3.105 3.105 4 2 4 C 0.895 4 0 3.105 0 2 Z" fill="transparent" height="4px" id="aBzgyASOc" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(2 18)" width="4px"/></svg>';
const getProps = ({
    color,
    height,
    id,
    width,
    width1,
    ...props
}) => {
    return { ...props,
        JEeZYcamG: width1 ? ? props.JEeZYcamG ? ? 2,
        P_DcoRcrY: color ? ? props.P_DcoRcrY ? ? "rgb(0, 0, 0)"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        P_DcoRcrY,
        JEeZYcamG,
        ...restProps
    } = getProps(props);
    const href = useSVGTemplate("3008297960", svg);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-Efhma", className),
        layoutId: layoutId,
        ref: ref,
        role: "presentation",
        style: {
            "--1m973uw": P_DcoRcrY,
            "--js9iwy": JEeZYcamG,
            ...style
        },
        viewBox: "0 0 24 24",
        children: /*#__PURE__*/ _jsx("use", {
            href: href
        })
    });
});
const css = [`.framer-Efhma { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"P_DcoRcrY":"color","JEeZYcamG":"width1"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Sparkles","color":{"type":"variable","value":"1m973uw"},"set":{"localId":"vectorSet/ZsiCCGPvG","id":"ZsiCCGPvG","moduleId":"Y7SpbVH16cWqMhj75z1M"}}
 */
const Icon = withCSS(Component, css, "framer-Efhma");
Icon.displayName = "Sparkles";
export default Icon;
addPropertyControls(Icon, {
    P_DcoRcrY: {
        defaultValue: "rgb(0, 0, 0)",
        hidden: false,
        title: "Color",
        type: ControlType.Color
    },
    JEeZYcamG: {
        defaultValue: 2,
        displayStepper: true,
        hidden: false,
        max: 16,
        min: 1,
        title: "Width",
        type: ControlType.Number
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerIntrinsicHeight": "24",
                "framerSupportedLayoutHeight": "any-prefer-fixed",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "24",
                "framerVector": "{\"name\":\"Sparkles\",\"color\":{\"type\":\"variable\",\"value\":\"1m973uw\"},\"set\":{\"localId\":\"vectorSet/ZsiCCGPvG\",\"id\":\"ZsiCCGPvG\",\"moduleId\":\"Y7SpbVH16cWqMhj75z1M\"}}",
                "framerContractVersion": "1",
                "framerVariables": "{\"P_DcoRcrY\":\"color\",\"JEeZYcamG\":\"width1\"}",
                "framerSupportedLayoutWidth": "any-prefer-fixed"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}