// Generated by Framer (7587b09)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    RichText,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS,
    withFX
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/ygUs1FpB51WZwbYbKRfU/8lrom3UF8a5K5kLueBBT/wjtHCGvqq.js";
const MotionDivWithFX = withFX(motion.div);
const enabledGestures = {
    TzCkFXOc9: {
        hover: true,
        pressed: true
    }
};
const cycleOrder = ["TzCkFXOc9", "w_GeZE8ar", "HSjp3IJCk", "GQyDEf0PM", "bOgR4dRb4"];
const serializationHash = "framer-RU3sO";
const variantClassNames = {
    bOgR4dRb4: "framer-v-17fkwi9",
    GQyDEf0PM: "framer-v-1r84aih",
    HSjp3IJCk: "framer-v-1os9c97",
    TzCkFXOc9: "framer-v-bceibw",
    w_GeZE8ar: "framer-v-fzpmy3"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const yHJH9jlGv = undefined;
const Jgx8a_h9r = undefined;
const BTOCn4_SA = undefined;
const transition1 = {
    delay: 0,
    duration: .2,
    ease: [.44, 0, .56, 1],
    type: "tween"
};
const transition2 = {
    delay: 0,
    duration: 1,
    ease: [0, 0, 1, 1],
    type: "tween"
};
const animation = {
    opacity: 1,
    rotate: 360,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: 0
};
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    Default: "TzCkFXOc9",
    Disabled: "HSjp3IJCk",
    Error: "bOgR4dRb4",
    Loading: "w_GeZE8ar",
    Success: "GQyDEf0PM"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    click,
    fill,
    height,
    id,
    title,
    width,
    ...props
}) => {
    return { ...props,
        BTOCn4_SA: title ? ? props.BTOCn4_SA ? ? "Submit",
        Jgx8a_h9r: click ? ? props.Jgx8a_h9r,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "TzCkFXOc9",
        yHJH9jlGv: fill ? ? props.yHJH9jlGv ? ? "var(--token-c1f30440-96cf-4826-9022-8bb46c0cd1a3, rgb(35, 35, 35))"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        BTOCn4_SA,
        yHJH9jlGv,
        Jgx8a_h9r,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "TzCkFXOc9",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTap1d3l0z4 = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (Jgx8a_h9r) {
            const res = await Jgx8a_h9r(...args);
            if (res === false) return false;
        }
    });
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = () => {
        if (baseVariant === "w_GeZE8ar") return true;
        return false;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.button, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-bceibw", className, classNames),
                    "data-framer-name": "Default",
                    "data-highlight": true,
                    "data-reset": "button",
                    layoutDependency: layoutDependency,
                    layoutId: "TzCkFXOc9",
                    onTap: onTap1d3l0z4,
                    ref: refBinding,
                    style: {
                        backgroundColor: yHJH9jlGv,
                        borderBottomLeftRadius: 6,
                        borderBottomRightRadius: 6,
                        borderTopLeftRadius: 6,
                        borderTopRightRadius: 6,
                        opacity: 1,
                        ...style
                    },
                    variants: {
                        "TzCkFXOc9-hover": {
                            backgroundColor: "var(--token-847720cf-a3a9-4922-bb4c-bbba010634be, rgb(247, 247, 247))",
                            opacity: 1
                        },
                        "TzCkFXOc9-pressed": {
                            backgroundColor: "var(--token-847720cf-a3a9-4922-bb4c-bbba010634be, rgb(247, 247, 247))",
                            opacity: 1
                        },
                        bOgR4dRb4: {
                            backgroundColor: "var(--token-c1f30440-96cf-4826-9022-8bb46c0cd1a3, rgb(35, 35, 35))",
                            opacity: 1
                        },
                        GQyDEf0PM: {
                            backgroundColor: "var(--token-c1f30440-96cf-4826-9022-8bb46c0cd1a3, rgb(35, 35, 35))",
                            opacity: 1
                        },
                        HSjp3IJCk: {
                            opacity: .5
                        }
                    },
                    ...addPropertyOverrides({
                        "TzCkFXOc9-hover": {
                            "data-framer-name": undefined
                        },
                        "TzCkFXOc9-pressed": {
                            "data-framer-name": undefined
                        },
                        bOgR4dRb4: {
                            "data-framer-name": "Error"
                        },
                        GQyDEf0PM: {
                            "data-framer-name": "Success"
                        },
                        HSjp3IJCk: {
                            "data-framer-name": "Disabled"
                        },
                        w_GeZE8ar: {
                            "data-framer-name": "Loading"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1q0gp8n",
                        "data-framer-name": "Default",
                        layoutDependency: layoutDependency,
                        layoutId: "uF1xv73h7",
                        style: {
                            scale: 1
                        },
                        variants: {
                            "TzCkFXOc9-pressed": {
                                scale: .8
                            }
                        },
                        children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-1icnjz7",
                                    "data-styles-preset": "wjtHCGvqq",
                                    dir: "auto",
                                    style: {
                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-0f516fd4-65c7-4b64-880e-09084b80b9c7, rgb(255, 255, 255)))"
                                    },
                                    children: "Submit"
                                })
                            }),
                            className: "framer-1qgyyzq",
                            "data-framer-name": "Text",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "B_C6pJ15a",
                            style: {
                                "--extracted-r6o4lv": "var(--token-0f516fd4-65c7-4b64-880e-09084b80b9c7, rgb(255, 255, 255))",
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: BTOCn4_SA,
                            variants: {
                                "TzCkFXOc9-hover": {
                                    "--extracted-r6o4lv": "var(--token-c1f30440-96cf-4826-9022-8bb46c0cd1a3, rgb(35, 35, 35))"
                                },
                                "TzCkFXOc9-pressed": {
                                    "--extracted-r6o4lv": "var(--token-c1f30440-96cf-4826-9022-8bb46c0cd1a3, rgb(35, 35, 35))"
                                }
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                "TzCkFXOc9-hover": {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            className: "framer-styles-preset-1icnjz7",
                                            "data-styles-preset": "wjtHCGvqq",
                                            dir: "auto",
                                            style: {
                                                "--framer-text-color": "var(--extracted-r6o4lv, var(--token-c1f30440-96cf-4826-9022-8bb46c0cd1a3, rgb(35, 35, 35)))"
                                            },
                                            children: "Submit"
                                        })
                                    })
                                },
                                "TzCkFXOc9-pressed": {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            className: "framer-styles-preset-1icnjz7",
                                            "data-styles-preset": "wjtHCGvqq",
                                            dir: "auto",
                                            style: {
                                                "--framer-text-color": "var(--extracted-r6o4lv, var(--token-c1f30440-96cf-4826-9022-8bb46c0cd1a3, rgb(35, 35, 35)))"
                                            },
                                            children: "Submit"
                                        })
                                    })
                                }
                            }, baseVariant, gestureVariant)
                        })
                    }), isDisplayed() && /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1s00uri",
                        "data-framer-name": "Spinner",
                        layoutDependency: layoutDependency,
                        layoutId: "RdBQFNC1S",
                        style: {
                            mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
                            WebkitMask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add"
                        },
                        children: /*#__PURE__*/ _jsx(MotionDivWithFX, {
                            __framer__loop: animation,
                            __framer__loopEffectEnabled: true,
                            __framer__loopRepeatDelay: 0,
                            __framer__loopRepeatType: "loop",
                            __framer__loopTransition: transition2,
                            __perspectiveFX: false,
                            __smartComponentFX: true,
                            __targetOpacity: 1,
                            className: "framer-7ix94t",
                            "data-framer-name": "Conic",
                            layoutDependency: layoutDependency,
                            layoutId: "Nz4kJbP5H",
                            style: {
                                background: "conic-gradient(from 180deg at 50% 50%, rgb(68, 204, 255) 0deg, rgb(68, 204, 255) 360deg)",
                                backgroundColor: "rgb(68, 204, 255)",
                                mask: "none",
                                WebkitMask: "none"
                            },
                            variants: {
                                w_GeZE8ar: {
                                    background: "conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 7.208614864864882deg, rgb(255, 255, 255) 342deg)",
                                    backgroundColor: "rgba(0, 0, 0, 0)",
                                    mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
                                    WebkitMask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add"
                                }
                            },
                            children: /*#__PURE__*/ _jsx(motion.div, {
                                className: "framer-gdtp8t",
                                "data-framer-name": "Rounding",
                                layoutDependency: layoutDependency,
                                layoutId: "vy38V9yWv",
                                style: {
                                    backgroundColor: "var(--token-5c4b1449-c670-480a-8558-944f8cd8cf27, rgb(254, 250, 243))",
                                    borderBottomLeftRadius: 1,
                                    borderBottomRightRadius: 1,
                                    borderTopLeftRadius: 1,
                                    borderTopRightRadius: 1
                                },
                                transformTemplate: transformTemplate1
                            })
                        })
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-RU3sO.framer-1qqwpht, .framer-RU3sO .framer-1qqwpht { display: block; }", ".framer-RU3sO.framer-bceibw { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 48px; justify-content: center; overflow: hidden; padding: 0px 24px 0px 24px; position: relative; width: 97px; will-change: var(--framer-will-change-override, transform); }", ".framer-RU3sO .framer-1q0gp8n { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; z-index: 1; }", ".framer-RU3sO .framer-1qgyyzq { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-RU3sO .framer-1s00uri { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); overflow: hidden; position: relative; width: 20px; }", ".framer-RU3sO .framer-7ix94t { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }", ".framer-RU3sO .framer-gdtp8t { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 2px); left: 50%; overflow: visible; position: absolute; top: 0px; width: 2px; }", ".framer-RU3sO.framer-v-fzpmy3 .framer-7ix94t { overflow: hidden; }", ".framer-RU3sO.framer-v-1r84aih.framer-bceibw, .framer-RU3sO.framer-v-17fkwi9.framer-bceibw { width: min-content; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 48
 * @framerIntrinsicWidth 97
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"w_GeZE8ar":{"layout":["fixed","fixed"]},"HSjp3IJCk":{"layout":["fixed","fixed"]},"GQyDEf0PM":{"layout":["auto","fixed"]},"bOgR4dRb4":{"layout":["auto","fixed"]},"znKx2wbBI":{"layout":["fixed","fixed"]},"FdC_pmQEv":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"BTOCn4_SA":"title","yHJH9jlGv":"fill","Jgx8a_h9r":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerjlnDoWtXZ = withCSS(Component, css, "framer-RU3sO");
export default FramerjlnDoWtXZ;
FramerjlnDoWtXZ.displayName = "Form Submit Button";
FramerjlnDoWtXZ.defaultProps = {
    height: 48,
    width: 97
};
addPropertyControls(FramerjlnDoWtXZ, {
    variant: {
        options: ["TzCkFXOc9", "w_GeZE8ar", "HSjp3IJCk", "GQyDEf0PM", "bOgR4dRb4"],
        optionTitles: ["Default", "Loading", "Disabled", "Success", "Error"],
        title: "Variant",
        type: ControlType.Enum
    },
    BTOCn4_SA: {
        defaultValue: "Submit",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    onBTOCn4_SAChange: {
        changes: "BTOCn4_SA",
        type: ControlType.ChangeHandler
    },
    yHJH9jlGv: {
        defaultValue: 'var(--token-c1f30440-96cf-4826-9022-8bb46c0cd1a3, rgb(35, 35, 35)) /* {"name":"Boldest"} */',
        title: "Fill",
        type: ControlType.Color
    },
    Jgx8a_h9r: {
        title: "Click",
        type: ControlType.EventHandler
    }
});
addFonts(FramerjlnDoWtXZ, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerjlnDoWtXZ",
            "slots": [],
            "annotations": {
                "framerVariables": "{\"BTOCn4_SA\":\"title\",\"yHJH9jlGv\":\"fill\",\"Jgx8a_h9r\":\"click\"}",
                "framerAutoSizeImages": "true",
                "framerContractVersion": "1",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"w_GeZE8ar\":{\"layout\":[\"fixed\",\"fixed\"]},\"HSjp3IJCk\":{\"layout\":[\"fixed\",\"fixed\"]},\"GQyDEf0PM\":{\"layout\":[\"auto\",\"fixed\"]},\"bOgR4dRb4\":{\"layout\":[\"auto\",\"fixed\"]},\"znKx2wbBI\":{\"layout\":[\"fixed\",\"fixed\"]},\"FdC_pmQEv\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerDisplayContentsDiv": "false",
                "framerImmutableVariables": "true",
                "framerIntrinsicHeight": "48",
                "framerIntrinsicWidth": "97",
                "framerColorSyntax": "true",
                "framerComponentViewportWidth": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./jlnDoWtXZ.map