// Generated by Framer (7587b09)
import {
    addPropertyControls as e,
    ControlType as t,
    QueryEngine as l
} from "framer";
import {
    DatabaseCollection as r,
    DatabaseDictionaryIndex as a
} from "./SUX7xTy4J-0.js";
import {
    getRichTextJsonResolver as i
} from "./SUX7xTy4J-1.js";
let o = {
        a1rJujB6e: {
            isNullable: !0,
            type: t.String
        },
        c1_wxtNpV: {
            isNullable: !0,
            type: t.String
        },
        createdAt: {
            isNullable: !0,
            type: t.Date
        },
        FcRhEM_pO: {
            isNullable: !0,
            type: t.String
        },
        id: {
            isNullable: !1,
            type: t.String
        },
        nextItemId: {
            isNullable: !0,
            type: t.String
        },
        previousItemId: {
            isNullable: !0,
            type: t.String
        },
        updatedAt: {
            isNullable: !0,
            type: t.Date
        },
        YEAnW6ACw: {
            isNullable: !0,
            type: t.RichText
        }
    },
    m = ["id"],
    c = {
        type: 1
    },
    n = ["previousItemId"],
    d = ["nextItemId"],
    u = ["id", "c1_wxtNpV"],
    p = ["c1_wxtNpV", "id"],
    f = ["a1rJujB6e"],
    s = {
        type: 0
    },
    y = ["FcRhEM_pO"],
    x = ["YEAnW6ACw"],
    w = ["c1_wxtNpV"],
    S = [],
    h = e => {
        let t = S[e];
        if (t) return t().then(e => e.default);
    },
    N = {},
    g = i(N),
    U = new l,
    I = {
        collectionByLocaleId: {
            default: new r({
                chunks: [new URL("./SUX7xTy4J-chunk-default-0.framercms", "https://framerusercontent.com/modules/loOLMYMxLRjzpvfqqItG/M4mNdDEHirBg4Zqik40F/SUX7xTy4J.js").href.replace("/modules/", "/cms/")],
                id: "92c6b67a-f583-48c9-afab-db015b854337default",
                indexes: [new a({
                    collation: c,
                    collectionSchema: o,
                    fieldNames: m,
                    range: {
                        from: 0,
                        to: 385
                    },
                    url: new URL("./SUX7xTy4J-indexes-default-0.framercms", "https://framerusercontent.com/modules/loOLMYMxLRjzpvfqqItG/M4mNdDEHirBg4Zqik40F/SUX7xTy4J.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: c,
                    collectionSchema: o,
                    fieldNames: n,
                    range: {
                        from: 385,
                        to: 769
                    },
                    url: new URL("./SUX7xTy4J-indexes-default-0.framercms", "https://framerusercontent.com/modules/loOLMYMxLRjzpvfqqItG/M4mNdDEHirBg4Zqik40F/SUX7xTy4J.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: c,
                    collectionSchema: o,
                    fieldNames: d,
                    range: {
                        from: 769,
                        to: 1149
                    },
                    url: new URL("./SUX7xTy4J-indexes-default-0.framercms", "https://framerusercontent.com/modules/loOLMYMxLRjzpvfqqItG/M4mNdDEHirBg4Zqik40F/SUX7xTy4J.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: c,
                    collectionSchema: o,
                    fieldNames: u,
                    range: {
                        from: 1149,
                        to: 1822
                    },
                    url: new URL("./SUX7xTy4J-indexes-default-0.framercms", "https://framerusercontent.com/modules/loOLMYMxLRjzpvfqqItG/M4mNdDEHirBg4Zqik40F/SUX7xTy4J.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: c,
                    collectionSchema: o,
                    fieldNames: p,
                    range: {
                        from: 1822,
                        to: 2495
                    },
                    url: new URL("./SUX7xTy4J-indexes-default-0.framercms", "https://framerusercontent.com/modules/loOLMYMxLRjzpvfqqItG/M4mNdDEHirBg4Zqik40F/SUX7xTy4J.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: s,
                    collectionSchema: o,
                    fieldNames: f,
                    range: {
                        from: 2495,
                        to: 3279
                    },
                    url: new URL("./SUX7xTy4J-indexes-default-0.framercms", "https://framerusercontent.com/modules/loOLMYMxLRjzpvfqqItG/M4mNdDEHirBg4Zqik40F/SUX7xTy4J.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: s,
                    collectionSchema: o,
                    fieldNames: y,
                    range: {
                        from: 3279,
                        to: 3671
                    },
                    url: new URL("./SUX7xTy4J-indexes-default-0.framercms", "https://framerusercontent.com/modules/loOLMYMxLRjzpvfqqItG/M4mNdDEHirBg4Zqik40F/SUX7xTy4J.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: s,
                    collectionSchema: o,
                    fieldNames: x,
                    range: {
                        from: 3671,
                        to: 8625
                    },
                    url: new URL("./SUX7xTy4J-indexes-default-0.framercms", "https://framerusercontent.com/modules/loOLMYMxLRjzpvfqqItG/M4mNdDEHirBg4Zqik40F/SUX7xTy4J.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: s,
                    collectionSchema: o,
                    fieldNames: w,
                    range: {
                        from: 8625,
                        to: 9082
                    },
                    url: new URL("./SUX7xTy4J-indexes-default-0.framercms", "https://framerusercontent.com/modules/loOLMYMxLRjzpvfqqItG/M4mNdDEHirBg4Zqik40F/SUX7xTy4J.js").href.replace("/modules/", "/cms/")
                })],
                resolveRichText: g,
                resolveVectorSetItem: h,
                schema: o
            })
        },
        displayName: "FAQ",
        id: "92c6b67a-f583-48c9-afab-db015b854337"
    };
export default I;
e(I, {
    a1rJujB6e: {
        defaultValue: "",
        title: "Q",
        type: t.String
    },
    FcRhEM_pO: {
        dataIdentifier: "local-module:collection/SGRd1o9yv:default",
        title: "Categories",
        type: t.CollectionReference
    },
    YEAnW6ACw: {
        defaultValue: "",
        title: "A",
        type: t.RichText
    },
    c1_wxtNpV: {
        preventLocalization: !1,
        title: "Slug",
        type: t.String
    },
    createdAt: {
        title: "Created",
        type: t.Date
    },
    updatedAt: {
        title: "Updated",
        type: t.Date
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/SUX7xTy4J:default",
        title: "Previous",
        type: t.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/SUX7xTy4J:default",
        title: "Next",
        type: t.CollectionReference
    }
});
export const enumToDisplayNameFunctions = {};
export const utils = {
    async getSlugByRecordId(e, t) {
        let [l] = await U.query({
            from: {
                data: I,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "c1_wxtNpV",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, t);
        return l ? .c1_wxtNpV;
    },
    async getRecordIdBySlug(e, t) {
        let [l] = await U.query({
            from: {
                data: I,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "c1_wxtNpV",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, t);
        return l ? .id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerAutoSizeImages": "true",
                "framerColorSyntax": "false",
                "framerCollectionId": "SUX7xTy4J",
                "framerContractVersion": "1",
                "framerData": "true",
                "framerSlug": "c1_wxtNpV",
                "framerRecordIdKey": "id",
                "framerCollectionUtils": "1",
                "framerEnumToDisplayNameUtils": "2"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}