// Generated by Framer (747ab96)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    cx,
    motion,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const mask = 'url(\'data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 300 134" xmlns="http://www.w3.org/2000/svg"><path d="M 0 125.697 C 43.061 -43.161 79.205 102.663 143.928 102.663 C 223.106 98.344 231.32 -64.954 300 29.197" fill="transparent" height="125.697142801419px" id="zRqkyIWEB" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="miter" stroke-miterlimit="10" stroke-width="1.8" stroke="var(--token-2bd3ab0c-0a6a-49df-8ca5-ec67b2a8804a, rgb(143, 205, 255))" transform="translate(0 8.303)" width="300px"/></svg>\') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)';
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(motion.div, { ...rest,
        layoutId: layoutId,
        ref: ref
    }) : /*#__PURE__*/ _jsx("div", { ...rest,
        ref: ref
    });
});
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-wH93O", className),
        layoutId: layoutId,
        ref: ref,
        style: { ...style
        }
    });
});
const css = [`.framer-wH93O { -webkit-mask: ${mask}; aspect-ratio: 2.2388059701492535; background-color: var(--token-2bd3ab0c-0a6a-49df-8ca5-ec67b2a8804a, #8fcdff); mask: ${mask}; width: 300px; }`];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 300
 * @framerIntrinsicHeight 134
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerImmutableVariables true
 * @framerVector {"name":"Vector","color":{"type":"static","value":"var(--token-2bd3ab0c-0a6a-49df-8ca5-ec67b2a8804a, rgb(143, 205, 255))"},"set":{"localId":"vectorSet/AMH_leyid","id":"AMH_leyid","moduleId":"x6xiKTLoBxKwreQYyqW4"}}
 */
const Icon = withCSS(Component, css, "framer-wH93O");
Icon.displayName = "Vector";
export default Icon;
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "300",
                "framerIntrinsicHeight": "134",
                "framerImmutableVariables": "true",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerSupportedLayoutHeight": "any-prefer-fixed",
                "framerVector": "{\"name\":\"Vector\",\"color\":{\"type\":\"static\",\"value\":\"var(--token-2bd3ab0c-0a6a-49df-8ca5-ec67b2a8804a, rgb(143, 205, 255))\"},\"set\":{\"localId\":\"vectorSet/AMH_leyid\",\"id\":\"AMH_leyid\",\"moduleId\":\"x6xiKTLoBxKwreQYyqW4\"}}",
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}