// Generated by Framer (c8e5bf6)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import BackgroundPattern from "https://framerusercontent.com/modules/sbWEZhpbWDNQ64mRZcmT/Tf0ECRTfyblFDXnVL11a/Background_Pattern.js";
const BackgroundPatternFonts = getFonts(BackgroundPattern);
const cycleOrder = ["yLgjooLvj", "MBdTXMOHx", "YG_bSnlhp", "SzmwBsrY5", "jVOEEDxX0"];
const serializationHash = "framer-LYfTr";
const variantClassNames = {
    jVOEEDxX0: "framer-v-1gvmiei",
    MBdTXMOHx: "framer-v-1lelii8",
    SzmwBsrY5: "framer-v-1nijq0p",
    YG_bSnlhp: "framer-v-1l6b1cb",
    yLgjooLvj: "framer-v-rrv05o"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    "Blue • A": "MBdTXMOHx",
    "Green • A": "YG_bSnlhp",
    "Purple • A": "yLgjooLvj",
    Orange: "SzmwBsrY5",
    Yellow: "jVOEEDxX0"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "yLgjooLvj"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "yLgjooLvj",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-rrv05o", className, classNames),
                    "data-framer-name": "Purple • A",
                    layoutDependency: layoutDependency,
                    layoutId: "yLgjooLvj",
                    ref: refBinding,
                    style: {
                        backgroundColor: "var(--token-0b5bd236-3a12-4bd0-8820-4c530465092f, rgb(225, 193, 255))",
                        ...style
                    },
                    variants: {
                        jVOEEDxX0: {
                            backgroundColor: "var(--token-31f8b27a-6369-4fb3-908e-daa328a68d14, rgb(239, 255, 45))"
                        },
                        MBdTXMOHx: {
                            backgroundColor: "var(--token-2bd3ab0c-0a6a-49df-8ca5-ec67b2a8804a, rgb(143, 205, 255))"
                        },
                        SzmwBsrY5: {
                            backgroundColor: "var(--token-9046c851-324f-42bf-b158-0b8ff5353d45, rgb(255, 197, 91))"
                        },
                        YG_bSnlhp: {
                            backgroundColor: "var(--token-8c2490e6-553f-4b78-874c-6b3f130509d6, rgb(142, 255, 111))"
                        }
                    },
                    ...addPropertyOverrides({
                        jVOEEDxX0: {
                            "data-framer-name": "Yellow"
                        },
                        MBdTXMOHx: {
                            "data-framer-name": "Blue • A"
                        },
                        SzmwBsrY5: {
                            "data-framer-name": "Orange"
                        },
                        YG_bSnlhp: {
                            "data-framer-name": "Green • A"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-1ce2wfo-container",
                            isAuthoredByUser: true,
                            isModuleExternal: true,
                            layoutDependency: layoutDependency,
                            layoutId: "urQrL6TNi-container",
                            nodeId: "urQrL6TNi",
                            rendersWithMotion: true,
                            scopeId: "o8ME_PMdH",
                            children: /*#__PURE__*/ _jsx(BackgroundPattern, {
                                backgroundColor: "rgba(0, 0, 0, 0)",
                                dotSize: 1.2,
                                fade: true,
                                fadeIntensity: 90,
                                fadeShape: "circle",
                                gap: 15,
                                height: "100%",
                                id: "urQrL6TNi",
                                layoutId: "urQrL6TNi",
                                patternColor: "rgb(5, 64, 227)",
                                patternOpacity: .4,
                                patternSize: 40,
                                patternType: "cross",
                                strokeWidth: 3,
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                width: "100%",
                                ...addPropertyOverrides({
                                    jVOEEDxX0: {
                                        patternColor: "rgb(85, 25, 140)",
                                        patternType: "texture"
                                    },
                                    MBdTXMOHx: {
                                        patternType: "xo"
                                    },
                                    SzmwBsrY5: {
                                        patternColor: "rgb(138, 96, 18)",
                                        patternType: "signal"
                                    },
                                    YG_bSnlhp: {
                                        patternSize: 20,
                                        patternType: "architect"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-LYfTr.framer-dwevgk, .framer-LYfTr .framer-dwevgk { display: block; }", ".framer-LYfTr.framer-rrv05o { height: 120px; position: relative; width: 370px; }", ".framer-LYfTr .framer-1ce2wfo-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 120
 * @framerIntrinsicWidth 370
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"MBdTXMOHx":{"layout":["fixed","fixed"]},"YG_bSnlhp":{"layout":["fixed","fixed"]},"SzmwBsrY5":{"layout":["fixed","fixed"]},"jVOEEDxX0":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const Framero8ME_PMdH = withCSS(Component, css, "framer-LYfTr");
export default Framero8ME_PMdH;
Framero8ME_PMdH.displayName = "Graphic";
Framero8ME_PMdH.defaultProps = {
    height: 120,
    width: 370
};
addPropertyControls(Framero8ME_PMdH, {
    variant: {
        options: ["yLgjooLvj", "MBdTXMOHx", "YG_bSnlhp", "SzmwBsrY5", "jVOEEDxX0"],
        optionTitles: ["Purple • A", "Blue • A", "Green • A", "Orange", "Yellow"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(Framero8ME_PMdH, [{
    explicitInter: true,
    fonts: []
}, ...BackgroundPatternFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "Framero8ME_PMdH",
            "slots": [],
            "annotations": {
                "framerColorSyntax": "true",
                "framerContractVersion": "1",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"MBdTXMOHx\":{\"layout\":[\"fixed\",\"fixed\"]},\"YG_bSnlhp\":{\"layout\":[\"fixed\",\"fixed\"]},\"SzmwBsrY5\":{\"layout\":[\"fixed\",\"fixed\"]},\"jVOEEDxX0\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerDisplayContentsDiv": "false",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "370",
                "framerAutoSizeImages": "true",
                "framerIntrinsicHeight": "120",
                "framerComponentViewportWidth": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./o8ME_PMdH.map